service: toolink-database

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

resources:
  Resources:
    # Categories Table
    CategoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Generate a name based on the stage
        TableName: ${self:custom.stage}-categories
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: categoryId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: categoryId
            KeyType: RANGE
        # Set the capacity based on the stage
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}
    # Links Table
    LinksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Generate a name based on the stage
        TableName: ${self:custom.stage}-links
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: linkId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: linkId
            KeyType: RANGE
        # Set the capacity based on the stage
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}         

  Outputs:
    CategoriesTableArn:
      Value:
         Fn::GetAtt:
          - CategoriesTable
          - Arn
      Export:
        Name: ${self:custom.stage}-CategoriesTableArn 

    CategoriesTableName:
      Value:
        Ref: CategoriesTable
      Export:
        Name: ${self:custom.stage}-CategoriesTable

    LinksTableArn:
      Value:
         Fn::GetAtt:
          - LinksTable
          - Arn
      Export:
        Name: ${self:custom.stage}-LinksTableArn

    LinksTableName:
      Value:
        Ref: LinksTable
      Export:
        Name: ${self:custom.stage}-LinksTable