service: toolink-api-billing

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Load our webpack config
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    # Load our secret environment variables based on the current stage.
    # Fallback to default if it is not in prod.
  environment: ${file(../../env.yml):${self:custom.stage}, file(../../env.yml):default}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  timeout: 10

  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiRootResourceId
  
  # These environment variables are made available to our functions
  # under process.env.
  environment:
    stripeSecretKey: ${self:custom.environment.STRIPE_SECRET_KEY}

functions:
  # Defines an HTTP API endpoint that calls the main function in charge.js
  # - path: url path is /billing/charge
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  charge:
      # Defines an HTTP API endpoint that calls the main function in charge.js
      # - path: url path is /billing/charge
      # - method: charge request
      handler: src/charge.main
      events:
        - http:
            path: billing/charge
            method: post
            cors: true
            authorizer: aws_iam
  customer:
      # Defines an HTTP API endpoint that calls the main function in customer.js
      # - path: url path is /billing/customer
      # - method: customer request
      handler: src/customer.main
      events:
        - http:
            path: billing/customer
            method: post
            cors: true
            authorizer: aws_iam
  subscription:
    # Defines an HTTP API endpoint that calls the main function in subscription.js
    # - path: url path is /billing/subscription
    # - method: customer request
    handler: src/subscription.main
    events:
      - http:
          path: billing/subscription
          method: post
          cors: true
          authorizer: aws_iam
  plan:
    # Defines an HTTP API endpoint that calls the main function in plan.js
    # - path: url path is billing/plan
    # - method: customer request
    handler: src/plan.main
    events:
      - http:
          path: billing/plan
          method: get
          cors: true
          authorizer: aws_iam          